### PR TITLE
Fork ocramius/package-versions to allow using Composer 2 on PHP >= 7.1

### PR DESCRIPTION
**Pull request by nicolas-grekas**
# Package Versions
  
This package is a fork of [`ocramius/package-versions`](https://packagist.org/packages/ocramius/package-versions).

The original package is compatible with Composer 2 only if PHP >= 7.4 is used.
This fork lowers this restriction and is compatible with Composer 2 on PHP >= 7.1.

Except minor changes made to provide compatibility with lower versions of PHP,
the source code is strictly kept in sync with the original.

See [Ocramius#133](https://github.com/Ocramius/PackageVersions/pull/133) for background.

### Installation

```sh
composer require suimarco/package-versions
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
/cc @ocramius FYI.

I'd like to provide a package that doesn't force PHP 7.4 when using Composer 2. I spotted this issue while trying to upgrade [symfony/demo](https://github.com/symfony/demo) and having Composer 2 locally. This is not possible right now because the demo app has an extra.platform.php entry that sticks to PHP 7.2.9, thus conflicts with the package-versions plugin. Removing that line would be a workaround we'd better not do: we want to ship a composer.lock file that works by default.

**Comment by Ocramius** [comment]
Not a big deal to have forks sitting around: the next version of `ocramius/package-versions` will be for `composer/composer:^2` and `php^7.4.7` anyway

**Comment by Ocramius** [comment]
FWIW, there's also `seldaek/package-versions` out there

**Comment by Seldaek** [comment]
https://github.com/composer/package-versions-deprecated is already there and ready to use, I'd advise abandoning this fork in favor of the composer one..

**Comment by nicolas-grekas** [comment]
Oh! I just lost some hours on this but I'm happy I won't spend more.
Merging Ocramius#133 would still save tremendous loads of WTH if you can reconsider @Ocramius 

Thanks for hints.

**Pull request closed without merging**
